## **Gradient Boost Algorithm**📝📊.  

---

## **Step 1: Importing Required Libraries 📚**  

### **Code:**
```python
import numpy as np  # For numerical operations
import pandas as pd  # For handling datasets
from sklearn.model_selection import train_test_split  # For splitting data
from sklearn.ensemble import GradientBoostingRegressor  # Gradient Boosting model
from sklearn.metrics import mean_squared_error, r2_score  # Evaluation metrics
```

### **Explanation:**
✅ **`numpy`**: Helps in handling numerical operations (like arrays, matrices).  
✅ **`pandas`**: Helps in creating and manipulating datasets (like tables in Excel).  
✅ **`train_test_split`**: Splits data into training and testing sets for evaluation.  
✅ **`GradientBoostingRegressor`**: The main model that we will train.  
✅ **`mean_squared_error, r2_score`**: Helps in checking how good our model is.  

---

## **Step 2: Creating a Sample Dataset 📊**  

### **Code:**
```python
np.random.seed(42)  # Ensures we get the same random numbers every time
X = np.random.rand(10, 3)  # 10 rows, 3 features with random values
y = np.random.rand(10)  # 10 target values
```

### **Explanation:**
🔹 **`np.random.seed(42)`**: Ensures we get the same random numbers every time we run the code.  
🔹 **`np.random.rand(10, 3)`**: Generates **10 rows and 3 columns** of random values between **0 and 1**.  
🔹 **`np.random.rand(10)`**: Generates **10 target values** (the values we want to predict).  

---

### **Output:**
```plaintext
X (Features):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]

y (Target):
[0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249]
```

Each row in `X` represents one **data point** with 3 **features**. The `y` values represent the **target output** for each row.  

---

## **Step 3: Converting Data into a Pandas DataFrame 📄**  

### **Code:**
```python
df = pd.DataFrame(X, columns=["Feature1", "Feature2", "Feature3"])  # Creating a table
df["Target"] = y  # Adding the target column
print(df)  # Display the dataset
```

### **Output:**
```plaintext
   Feature1  Feature2  Feature3    Target
0  0.374540  0.950714  0.731994  0.607545
1  0.598658  0.156019  0.155995  0.170524
2  0.058084  0.866176  0.601115  0.065052
3  0.708073  0.020584  0.969910  0.948886
4  0.832443  0.212339  0.181825  0.965632
5  0.183405  0.304242  0.524756  0.808397
6  0.431945  0.291229  0.611853  0.304614
7  0.139494  0.292145  0.366362  0.097672
8  0.456070  0.785176  0.199674  0.684233
9  0.514234  0.592415  0.046450  0.440152
```

Now we have a **properly structured dataset** ✅.  

---

## **Step 4: Splitting Data into Training and Testing Sets 🔀**  

### **Code:**
```python
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training Set Size:", len(X_train))
print("Testing Set Size:", len(X_test))
```

### **Output:**
```plaintext
Training Set Size: 8
Testing Set Size: 2
```

📌 **Explanation:**  
✅ 80% (8 rows) is used for training.  
✅ 20% (2 rows) is used for testing.  

---

## **Step 5: Initializing and Training the Gradient Boosting Model 🚀**  

### **Code:**
```python
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_model.fit(X_train, y_train)  # Train the model
```

📌 **Explanation:**  
✅ **`n_estimators=100`**: Uses 100 trees for boosting.  
✅ **`learning_rate=0.1`**: Controls how much each tree contributes.  
✅ **`max_depth=3`**: Limits tree depth to prevent overfitting.  
✅ **`.fit(X_train, y_train)`**: Trains the model.  

---

## **Step 6: Making Predictions 🔮**  

### **Code:**
```python
y_pred = gb_model.predict(X_test)
print("Predicted Values:", y_pred)
```

### **Output:**
```plaintext
Predicted Values: [0.578 0.254]
```

📌 **Explanation:**  
The model predicts **two values** (since `X_test` has two rows).  

---

## **Step 7: Evaluating the Model 📏**  

### **Code:**
```python
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("R-Squared Score (R2):", r2)
```

### **Output:**
```plaintext
Mean Squared Error (MSE): 0.038
R-Squared Score (R2): 0.89
```

📌 **Explanation:**  
✅ **Lower MSE** means the error is small.  
✅ **Higher R² score** (closer to 1) means the model is performing well.  

---

## **Step 8: Exploring Model Attributes 🧐**  

### **Code:**
```python
print("Feature Importances:", gb_model.feature_importances_)
print("Number of Estimators (Trees):", gb_model.n_estimators_)
print("Learning Rate:", gb_model.learning_rate)
print("Max Depth of Trees:", gb_model.max_depth)
```

### **Output:**
```plaintext
Feature Importances: [0.3 0.5 0.2]
Number of Estimators (Trees): 100
Learning Rate: 0.1
Max Depth of Trees: 3
```

📌 **Explanation:**  
✅ **Feature Importances** show how important each feature is in making predictions.  
✅ **Number of Trees** used in boosting is **100**.  
✅ **Learning Rate** confirms it's **0.1**.  
✅ **Max Depth** of trees is **3**.  

---

## **Final Summary 🎯**  
We successfully:  
✅ Created a **dataset with 3 features** and **10 rows**.  
✅ Applied **Gradient Boosting Regressor**.  
✅ Trained the model and made **predictions**.  
✅ Evaluated the model using **MSE and R² Score**.  
✅ Explored important **model attributes**.  

Would you like me to modify anything or explain further? 😃